//
//  URLMethods.swift
//  Lion Miles
//
//  Created by Arkmacbook on 22/10/20.
//

import UIKit

let login_URLMethod = "CheckIsAuthenticatedMobileApp"
let forgotPassword_URLMethod = "forgotPasswordMobileApp"
let memberVerification_URLMethod = "CheckCustomerExistancyAndVerificationJson"
let dashboard_URLMethod = "GetDashBoardDetailsApi"
let dashboardImages_URLMethod = "BindLandingImageList"
let myRedemptionList_URLMethod = "GetCatalogueDetails"
let myEarningList_URLMethod = "GetRewardTransactionDetailsMobileApp"
let myDreamGiftList_URLMethod = "GetDreamGiftDetails"
let syncStatusListing_URMethod = "GetQRCodeStatus"
let E_WarrantyListing_URLMethod = "GetEWarrantydetails"
let removeDreamGift_URLMethod = "SaveOrUpdateDreamGiftDetails"
let productCategory_URLMethod = "GetCatalogueCategoryDetails"
let productCatalogue_URLMethod = "GetCatalogueDetails"
let addToCart_URLMethod = "SaveCatalogueCartDetailsMobile"
let myCartList_URLMethod = "GetCatalogueCartDetailsMobile"
let updateMyCart_URLMethod = "UpdateCustomerCart"
let addToPlanner_URLMethod = "GetCatalogueDetails"
let plannerList_URLMethod = "GetRedemptionPlannerDetails"
let myProfile_URLMethod = "GetCustomerDetailsMobileApp"
let stateList_URLMethod = "GetStateDetailsMobileApp"
let cityList_URLMethod = "GetCityDetailsMobileApp"
let getOTP_URLMethod = "SaveAndGetOTPDetails"
let userStatus_URLMethod = "UserActiveOrInActive"
let redemptionSubmission_URLMethod = "SaveCatalogueRedemptionDetails"
let sendSMS_URL = "SendCatalogueRedemptionAlertMobileApp"
let sendSuccessURL = "SendSMSForSuccessfulRedemptionMobileApp"
let removePlannerURL = "GetPlannerAddedOrNot"
let areaList_URLMethod = "GetAreaDetails"
let saveEwarrentyDetails = "SaveEWarrantyDetails"
let downloadWarrentyURLMethod = "DownloadEwarranty"
let queryListing_URLMethod = "SaveCustomerQueryTicket"
let helpTopic_URLMethod = "GetHelpTopics"
let chatDetails_URLMethod = "GetQueryResponseInformation"
let newQuerySubmission_URLMethod = "SaveCustomerQueryTicket"
let chatListing_URLMethod = "GetQueryResponseInformation"
let chatSubmission_URLMethod = "SaveCustomerQueryTicket"
let offersandPromotions_URLMethod = "GetPromotionDetailsMobileApp"
let savedCodes_URLMethod = "SaveQRCodeDetailsBulk"
let getQRCodeStatus = "GetQRCodeStatus"
let menuList_URLMethod = "GetUserMenuDetails"
let historyNotification = "GetPushHistoryDetails"
let deleteAccountMethodName = "CustomerAccountDelete"
let panMethodName = "ValidatePanDetails"
let panSaveMethodName = "SaveCustomerPanDetails"
let GetPanDetails = "GetPanDetails"
let UpdateCustomerProfileMobileApp = "UpdateCustomerProfileMobileApp"
let getScratchCode_MethodName = "GetScratchCodeDetailsJson"
